### ISSUE TITLE
Docs: add dependency section

### ISSUE THREAD

**Issue by sebastianharko** [UltimateSoftware/surge#23]
### Is your feature request related to a problem? Please describe.
Yes, when a user is getting started and they are reading the docs, they want to know what dependencies they have to import.

## Describe the solution you'd like
Adding a dependency section in the docs.

## Describe alternatives you've considered
No alternatives, since we are using Paradox we only have one choice (https://developer.lightbend.com/docs/paradox/current/directives/dependencies.html)

## Additional context
N/A

**Comment by jeffboutotte** [comment]
Fixed by #22
