### ISSUE TITLE
Flaky unit/integration test ?

### ISSUE THREAD

**Issue by sebastianharko** [UltimateSoftware/surge#28]
Some of the unit/integration tests appear to be flaky

**Comment by jeffboutotte** [comment]
@zachary-rote can you take a look? Looks related to some of the new health reporting:
```
HealthSignalWindowActorSpec.HealthSignalWindowActor should tick
The code passed to eventually never returned normally. Attempted 42 times over 2.67888657785 minutes. Last failure message: 160 did not equal 5.
```

Also...does that really take over 2 minutes? Maybe on success it takes much less time, but that seems like a really long timeout?

**Comment by sebastianharko** [comment]
Closing this because most of these issues have been resolved
